import type { Step } from "@/lib/types";

export const sample: Record<Step, string[]> = {
  start: [],
  basics: [],
  certificates: [],
  tailor: [],
  finish: [],
  work: [
    "Demonstrated ability to work effectively both independently and as part of a team.",
    "Consistently met or exceeded set goals and deadlines, showcasing strong personal drive and initiative.",
    "Developed and implemented strategies to improve efficiency and productivity, resulting in significant performance improvements.",
    "Leveraged strong communication skills to build positive relationships with clients, colleagues, and management.",
    "Continually sought opportunities for professional development, staying up-to-date with industry trends and advancements.",
    "Exhibited strong problem-solving skills, often recognized for creative and effective solutions.",
    "Maintained a high level of accuracy and attention to detail in a fast-paced work environment.",
    "Contributed to a positive work culture with a friendly and cooperative attitude.",
    "Managed multiple tasks and projects simultaneously, demonstrating excellent time management skills.",
  ],
  education: [
    "Earned a Bachelor's/Master's degree in [Field of Study], demonstrating a strong academic performance.",
    "Participated in relevant coursework, including [Course Name], [Course Name], and [Course Name].",
    "Completed a capstone project on [Topic], showcasing the ability to apply learned concepts in a practical setting.",
    "Gained hands-on experience through lab work and practical assignments, enhancing understanding of [Subject].",
    "Actively participated in [Club/Activity], developing leadership and teamwork skills.",
    "Received [Scholarship/Award] for academic excellence and commitment to [Field of Study].",
    "Studied abroad in [Location], gaining a broader perspective and understanding of [Subject/Culture].",
    "Worked as a [Job Title] while studying, demonstrating strong time management skills.",
    "Attended multiple workshops and seminars on [Topic], staying up-to-date with the latest trends and advancements in the field.",
    "Volunteered for [Organization/Event], demonstrating a commitment to community service and personal growth.",
  ],
  skills: [
    "Effective Communication",
    "Team Collaboration",
    "Problem Solving",
    "Adaptability",
    "Time Management",
    "Leadership",
    "Detail Oriented",
    "Self-Motivation",
    "Technical Literacy",
    "Creative Thinking",
  ],
  accomplishments: [
    "Increased sales",
    "Boosted efficiency",
    "Achieved targets",
    "Led projects",
    "Improved processes",
    "Streamlined operations",
    "Enhanced teamwork",
    "Innovated solutions",
    "Awarded recognition",
    "Completed tasks",
  ],
  interests: [
    "Reading Books",
    "Traveling",
    "Photography",
    "Cooking",
    "Gardening",
    "Hiking",
    "Blogging",
    "Playing Chess",
    "Yoga",
    "Painting",
    "Volunteering",
    "Cycling",
    "Knitting",
    "Writing",
    "Running",
    "Music",
    "Dancing",
    "Bird Watching",
    "Fishing",
    "Pottery",
  ],
  summary: [
    "Highly motivated and diligent professional seeking to leverage proven skills in a challenging role.",
    "Experienced in a range of industries, bringing versatile knowledge and adaptability.",
    "Committed to achieving business objectives through strategic planning and effective decision-making.",
    "Strong communicator with a knack for fostering positive professional relationships.",
    "Continually seeking opportunities to grow professionally and contribute to a dynamic team.",
    "Proven ability to manage multiple tasks while maintaining a high level of attention to detail.",
    "Adept at identifying and solving problems to drive project success.",
    "Passionate about learning new skills and technologies to enhance job performance.",
    "Demonstrated leadership skills with the ability to motivate teams and implement effective training programs.",
    "Track record of improving operational processes and overall productivity.",
    "Skilled at building and maintaining professional relationships with clients and colleagues.",
    "Proactive and reliable, consistently achieving project goals and meeting deadlines.",
    "Committed to maintaining a high standard of performance and professionalism in all endeavors.",
    "Experienced in navigating high-stress situations and resolving conflicts effectively.",
    "Skilled at analyzing data and using it to drive decision-making processes.",
    "Known for a creative approach to problem-solving and the ability to think outside the box.",
    "Proven ability to adapt to new industries and roles quickly and effectively.",
    "Strong organizational skills with the ability to manage and prioritize multiple tasks simultaneously.",
    "Committed to continuous professional development and lifelong learning.",
    "Known for a positive attitude and the ability to bring energy and enthusiasm to any role.",
  ],
};
